#!/bin/bash
#
# Attach or create tmux session named the same as current directory.
#
# If called with --start or without a directory name ta will create a plain
# single window layout.
#
# When called to a specific directory ta will first ask which project to open
# then attach or create a new session.

not_in_tmux() {
  [ -z "$TMUX" ]
}
[ -z "$TMUX" ] && [ -z "$ZELLIJ" ]

DIR=$1

# If no arguments are passed in try to immediately attach or start without further input
echo "${DIR}"
if [ -z "$DIR" ]; then
  if not_in_tmux; then
    if session=$(tmux list-sessions -F "#{session_name}" | awk '!/^scratch-/{print; found=1; exit} END {exit !found}'); then
      tmux attach -t "${session}" && exit 1
    else
      DIR="--start"
    fi
  else
    exit 1
  fi
fi

# If --start was passed in immediately start a new session based on the current directory
if [ "${DIR}" == "--start" ]; then
  echo "starting"
  path_name="$(basename "$PWD" | tr . -)"
  session_name=${path_name//./_}
else
  # ask the user which directory to start in
  _session_name=$(find "${DIR}" -mindepth 1 -maxdepth 1 -type d ! -name ".*" -printf "%f\n" | fzf \
    --no-border \
    --height=100% \
    --bind 'ctrl-/:toggle-preview' \
    --exact \
    --reverse \
    --header="Select project from $(basename "${DIR}") >" \
    --preview-window=right,70%,border-none \
    --preview="echo ${DIR}/{} | xargs tree -C -L 1")
  session_name=${_session_name//./_}
  path_name=${DIR}/${_session_name}
fi

echo session name is "${session_name}"
echo path name is "${path_name}"

if [ -z "${session_name}" ]; then
  # operation cancelled by user
  exit 1
fi

session_exists() {
  # checks if the $session_name exists
  tmux has-session -t "=${session_name}"
}

create_detached_session() {
  if [ "${DIR}" == "--start" ]; then
    (
      TMUX=''
      tmux new-session -Ad -s "${session_name}" -c "${path_name}"
    )
  else
    (
      TMUX=''
      tmux new-session -Ad -s "${session_name}" -c "${path_name}"
      # tmux split-window -vb -t "$session_name" -c $path_name -p 70;
      tmux send-keys -t "${session_name}" "nvim '+Telescope find_files'" Enter
    )
  fi
}

create_if_needed_and_attach() {
  if not_in_tmux; then
    tmux new-session -As "${session_name}" -c "${path_name}"
  else
    if ! session_exists; then
      create_detached_session
    fi
    tmux switch-client -t "${session_name}"
  fi
}

attach_to_first_session() {
  tmux attach -t "$(tmux list-sessions -F "#{session_name}" | grep -v '^scratch-' | head -n 1)"
  tmux choose-tree -Z
}

create_if_needed_and_attach || attach_to_first_session
