#!/bin/bash

# format='#{session_name}: #{session_windows} windows (created #{t/f/%y-%m-%d %H#:%M#:%S:window_activity})'
# tmux ls -F "${format}"
# tmux list-sessions -F '#{?session_attached,,#{session_name}}'
tmux list-sessions -F '#{session_name} #{session_attached}' |
  awk '{
      if ($2==1) {
        # attached session in bold green
        printf "\033[38;5;223m%s\033[0m\n", $1
      } else {
        # not attached session normal
        print $1
      }
    }' |
  grep -v '^scratch-' |
  sed '/^$/d' |
  fzf \
    --ansi \
    --no-border \
    --height=100% \
    --bind 'ctrl-/:toggle-preview' \
    --exact \
    --reverse \
    --header "Switch to client >" \
    --preview-window=right,70%,border-none \
    --preview 'tmux capture-pane -pt {} | bat --color=always -pl sh' \
    --bind 'enter:execute(tmux switch-client -t {})+accept'
