#!/bin/bash

# shellcheck source=./utils
source "$(dirname "$0")/utils"

current_session=$(tmux display-message -p "#{session_name}")

toggle_scratch "$current_session" "scratch-youtube" "magic-tape.sh"
