#!/bin/bash

# shellcheck source=./utils
source "$(dirname "$0")/utils"

# Check if the current tmux session is 'scratch-bluetooth'
current_session=$(tmux display-message -p "#{session_name}")

if [[ "$current_session" == "scratch-bluetooth" ]]; then
  # If already in the scratch-bluetooth session, detach all scratch clients
  detach_scratch_clients
else
  # If scratch-bluetooth session exists, attach to it in a popup
  if tmux has-session -t scratch-bluetooth; then
    tmux display-popup -B -h 100% -w 100% -E 'tmux attach-session -t scratch-bluetooth'
  else
    # Otherwise, create the session, disable status bar, and attach
    tmux display-popup -B -h 100% -w 100% -E "tmux new-session -d -c $HOME -s scratch-bluetooth bluetuith && tmux set-option -t scratch-bluetooth status off && tmux attach-session -t scratch-bluetooth"
  fi
fi
