#!/bin/bash

# shellcheck source=./utils
source "$(dirname "$0")/utils"

# Check if the current tmux session is 'scratch-IRC'
current_session=$(tmux display-message -p "#{session_name}")

if [[ "$current_session" == "scratch-IRC" ]]; then
  # If already in the scratch-IRC session, detach all scratch clients
  detach_scratch_clients
else
  # If scratch-IRC session exists, attach to it in a popup
  if tmux has-session -t scratch-IRC; then
    tmux display-popup -B -h 100% -w 100% -E 'tmux attach-session -t scratch-IRC'
  else
    # Otherwise, create the session, disable status bar, and attach
    tmux display-popup -B -h 100% -w 100% -E "tmux new-session -d -c $HOME -s scratch-IRC weechat && tmux set-option -t scratch-IRC status off && tmux attach-session -t scratch-IRC"
  fi
fi
