#!/bin/bash

manpages=$(man -k .)

selection=$(printf "%s\n" "$manpages" | fzf \
  --no-border \
  --height=100% \
  --bind 'ctrl-/:toggle-preview' \
  --exact \
  --reverse \
  --cycle \
  --header "Open manual >" \
  --no-preview | awk '{print $1}') && [[ -n "$selection" ]] || exit 1

tmux split-window -h man "${selection}"
