#!/bin/bash

# shellcheck source=./utils
source "$(dirname "$0")/utils"

current_session=$(tmux display-message -p "#{session_name}")

toggle_scratch_popup "$current_session" "scratch-email" "neomutt"
