#!/bin/bash

tmux list-sessions -F '#{?session_attached,,#{session_name}}' |\
    sed '/^$/d' |\
    fzf --reverse --header jump-to-session --preview 'tmux capture-pane -pt {}' \
    	--bind 'enter:execute(tmux switch-client -t {})+accept'
