#!/bin/bash

# shellcheck source=./utils
source "$(dirname "$0")/utils"

# Check if the current tmux session is 'scratch-abook'
current_session=$(tmux display-message -p "#{session_name}")

if [[ "$current_session" == "scratch-abook" ]]; then
  # If already in the scratch-abook session, detach all scratch clients
  detach_scratch_clients
else
  # If scratch-abook session exists, attach to it in a popup
  if tmux has-session -t scratch-abook; then
    tmux display-popup -B -h 100% -w 100% -E 'tmux attach-session -t scratch-abook'
  else
    # Otherwise, create the session, disable status bar, and attach
    tmux display-popup -B -h 100% -w 100% -E "tmux new-session -d -c $HOME -s scratch-abook abook && tmux set-option -t scratch-abook status off && tmux attach-session -t scratch-abook"
  fi
fi
