#!/bin/bash

# shellcheck source=./utils
source "$(dirname "$0")/utils"

# Check if the current tmux session is 'scratch-orgmode'
current_session=$(tmux display-message -p "#{session_name}")

if [[ "$current_session" == "scratch-orgmode" ]]; then
  # If already in the scratch-orgmode session, detach all scratch clients
  detach_scratch_clients
else
  # If scratch-orgmode session exists, attach to it in a popup
  if tmux has-session -t scratch-orgmode; then
    tmux display-popup -B -h 100% -w 100% -E 'tmux attach-session -t scratch-orgmode'
  else
    # Otherwise, create the session, disable status bar, and attach
    tmux display-popup -B -h 100% -w 100% -E "tmux new-session -d -c $HOME -s scratch-orgmode nvim -c \":lua require(\\\"possession.session\\\").load(\\\"orgmode\\\")\" && tmux set-option -t scratch-orgmode status off && tmux attach-session -t scratch-orgmode"
  fi
fi
