#!/bin/bash

docsets=($(dasht-docsets))
declare search

# fzf multiselect with tab/shift-tab for search in multiple docsets
selection=$(printf "%s\n" "" "${docsets[@]}" | fzf \
  --no-border \
  --height=100% \
  --exact \
  --reverse \
  --multi \
  --header=select-docset \
  --no-preview | tr '\n' ' ') && [[ -n "$selection" ]] || exit 1
if [[ "$selection" = " " ]]; then
  echo -e "\033[32mAll docsets selected:\033[0m ${docsets[*]}\n"
else
  echo -e "\033[34mSelected docsets:\033[0m $selection\n"
fi

if ! read -r -e -p $'\033[33mEnter your search term:\033[0m ' search; then
  exit 1
fi

tmux split-window -h dasht "${search:- }" ${selection[*]}
