#!/bin/bash

# shellcheck source=./utils
source "$(dirname "$0")/utils"

# Check if the current tmux session is 'scratch-HTTP'
current_session=$(tmux display-message -p "#{session_name}")

if [[ "$current_session" == "scratch-HTTP" ]]; then
  # If already in the scratch-HTTP session, detach all scratch clients
  detach_scratch_clients
else
  # If scratch-HTTP session exists, attach to it in a popup
  if tmux has-session -t scratch-HTTP; then
    tmux display-popup -B -h 100% -w 100% -E 'tmux attach-session -t scratch-HTTP'
  else
    # Otherwise, create the session, disable status bar, and attach
    tmux display-popup -B -h 100% -w 100% -E "tmux new-session -d -c $HOME -s scratch-HTTP atac && tmux set-option -t scratch-HTTP status off && tmux attach-session -t scratch-HTTP"
  fi
fi
