#!/bin/bash

# shellcheck source=./utils
source "$(dirname "$0")/utils"

# Check if the current tmux session is 'scratch-calendar'
current_session=$(tmux display-message -p "#{session_name}")

if [[ "$current_session" == "scratch-calendar" ]]; then
  # If already in the scratch-calendar session, detach all scratch clients
  detach_scratch_clients
else
  # If scratch-calendar session exists, attach to it in a popup
  if tmux has-session -t scratch-calendar; then
    tmux display-popup -B -h 100% -w 100% -E 'tmux attach-session -t scratch-calendar'
  else
    # Otherwise, create the session, disable status bar, and attach
    tmux display-popup -B -h 100% -w 100% -E "tmux new-session -d -c $HOME -s scratch-calendar khal interactive && tmux set-option -t scratch-calendar status off && tmux attach-session -t scratch-calendar"
  fi
fi
