#!/bin/bash
set -euo pipefail

SESSION_DIR="$HOME/.local/share/nvim/possession"

select_sessions() {
  find "${SESSION_DIR}" -maxdepth 1 -name '*.json' -type f -printf '%f\n' |
    sed 's/\.json$//' |
    fzf \
      --expect enter,alt-enter \
      --no-border \
      --height=100% \
      --exact \
      --reverse \
      --cycle \
      --multi \
      --header "Select neovim session >" \
      --preview-window=right,70%,border-none \
      --preview="cat ${SESSION_DIR}/{}.json | jq .cwd | xargs tree -C -L 1"
}

not_in_tmux() {
  [[ -z "${TMUX:-}" ]] && [[ -z "${ZELLIJ:-}" ]]
}

session_exists() {
  tmux has-session -t "=${1}" 2>/dev/null
}

attach_session() {
  local tmux_session_name="${1}"
  if not_in_tmux; then
    tmux attach -t "${tmux_session_name}"
  else
    tmux switch-client -t "${tmux_session_name}"
  fi
}

create_session() {
  local tmux_session_name="${1}"
  local possession_session_name="${2}"
  local possession_session_cwd="${3}"

  if ! session_exists "${tmux_session_name}"; then
    (
      TMUX=''
      tmux new-session -Ad -s "${tmux_session_name}" -c "${possession_session_cwd}"
      tmux send-keys -t "${tmux_session_name}" "nvim -c ':lua require(\"possession.session\").load(\"${possession_session_name}\")'" Enter
    )
  fi

}

# For single-session: ensure tmux session and attach or switch to it
create_and_attach_session() {
  local possession_session_name="${1}"
  local tmux_session_name="${possession_session_name//./_}"
  local possession_session_cwd=$(jq -r '.cwd' "${SESSION_DIR}/${possession_session_name}.json")

  create_session "${tmux_session_name}" "${possession_session_name}" "${possession_session_cwd}"
  attach_session "${tmux_session_name}"
}

# For multi-session: create or attach all, don't switch
create_sessions_multi() {
  for sel in "$@"; do
    local possession_session_name="${sel}"
    local tmux_session_name="${possession_session_name//./_}"
    local possession_session_cwd=$(jq -r '.cwd' "${SESSION_DIR}/${possession_session_name}.json")
    create_session "${tmux_session_name}" "${possession_session_name}" "${possession_session_cwd}"
  done
}

main() {
  local selection result key
  result=$(select_sessions)
  key=$(head -n 1 <<<"${result}")
  selection=$(tail -n +2 <<<"${result}")
  [[ -z "${selection:-}" ]] && exit 1

  readarray -t selected_sessions <<<"$selection"

  if ((${#selected_sessions[@]} > 1)); then
    create_sessions_multi "${selected_sessions[@]}"
    exit 0
  else
    local possession_session_name="${selected_sessions[0]}"
    local tmux_session_name="${possession_session_name//./_}"
    local possession_session_cwd=$(jq -r '.cwd' "${SESSION_DIR}/${possession_session_name}.json")
    create_session "${tmux_session_name}" "${possession_session_name}" "${possession_session_cwd}"

    if [[ "${key:-}" == "enter" ]]; then
      attach_session "${tmux_session_name}"
    fi
  fi
}

main "$@"
