#!/bin/bash

detach_scratch_clients() {
  mapfile -t clients <<<"$(tmux list-clients -F '#{client_name} #{session_name}' | awk '$2 ~ /^scratch-/ {print $2}')"
  for client in "${clients[@]}"; do
    tmux detach-client -s "$client"
  done

}
